### ISSUE TITLE
Smooth Hover

### ISSUE THREAD

**Issue by AviationProgrammer** [hariketsheth/Grid-HoverEffect#1]
I was testing your project, but i figured out that while hovering over the board - the effect was a bit disrupted and it needs to be a bit fluent.

**Comment by hariketsheth** [comment]
> I was testing your project, but i figured out that while hovering over the board - the effect was a bit disrupted and it needs to be a bit fluent.

@AviationProgrammer From my end, the hover is smooth only. Still I will check for making it better. 
Thanks for your suggestion  :)
